version: '3.3'

services:

  #TODO need to finish the docker Compose to build docker containers for the services.
#  angular-service:
#    container_name: angularcontainer
#    build: ./favoriteGiphy
#    ports:
#      - '4200:4200' # Port mapping
#
#  auth-service:
#    container_name: authservicecontainer
#    build: ./auth-service
#    ports:
#      - '4200:4200'
#
#  eureka-service:
#    container_name: eurekacontainer
#    build: ./eureka-server
#    ports:
#      - '4200:4200'
#
#  login-service:
#    container_name: loginservicecontainer
#    build: ./login-service
#    ports:
#      - '4200:4200'
##    depends_on:
###      - mysqldb
#
#  profile-service:
#    container_name: profileservicecontainer
#    build: ./profile-service
#    ports:
#      - '4200:4200'
##    depends_on:
##      - mysqldb
#
#  user-service:
#    container_name: user-servicecontainer
#    build: ./user-service
#    ports:
#      - '4200:4200'
#    depends_on:
#      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
